# Generated by Django 4.2.2 on 2023-07-02 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appro', '0003_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts_utl', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('qts_prod', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('product_mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_mp', to='appro.product')),
                ('product_pf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appro.product')),
            ],
        ),
        migrations.CreateModel(
            name='LivraisonPv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appro.product')),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.pointvente')),
            ],
        ),
        migrations.CreateModel(
            name='LivraisonProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appro.product')),
            ],
        ),
        migrations.CreateModel(
            name='HasPf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appro.product')),
            ],
        ),
        migrations.CreateModel(
            name='HasMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appro.product')),
            ],
        ),
        migrations.CreateModel(
            name='DepotPt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appro.product')),
            ],
        ),
    ]
