# Generated by Django 4.2.2 on 2023-07-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0003_alter_hasqts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasqts',
            name='qts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
