# Generated by Django 4.2.2 on 2023-07-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0004_alter_hasqts_qts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='time_create',
        ),
        migrations.AddField(
            model_name='depotpt',
            name='heure',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderprod',
            name='heure',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpv',
            name='heure',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='heure',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
