# Generated by Django 4.2.2 on 2023-07-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0005_remove_production_time_create_depotpt_heure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraisonprod',
            name='qts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='livraisonpv',
            name='qts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
