# Generated by Django 4.2.2 on 2023-07-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0006_alter_livraisonprod_qts_alter_livraisonpv_qts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraisonpv',
            name='date',
        ),
        migrations.RemoveField(
            model_name='livraisonpv',
            name='pv',
        ),
        migrations.AddField(
            model_name='orderpv',
            name='pv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prod.pointvente'),
        ),
    ]
