# Generated by Django 4.2.2 on 2023-07-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0007_remove_livraisonpv_date_remove_livraisonpv_pv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotpt',
            name='qts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
