# Generated by Django 4.2.2 on 2023-06-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Gr', 'Gr'), ('Unité', 'Unité')], default='Kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.CharField(choices=[('produit fini', 'produit fini'), ('matière première', 'matière première')], max_length=255),
        ),
    ]
