# Generated by Django 4.2.2 on 2023-06-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0002_product_unit_alter_product_type_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products-images'),
        ),
    ]
