# Generated by Django 4.2.2 on 2023-07-03 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0003_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default='3edb180480', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='livraisongr',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appro.ordergr'),
        ),
    ]
