# Generated by Django 4.2.2 on 2023-07-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0004_ordergr_livraisongr_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotgr',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordergr',
            name='ref',
            field=models.CharField(default='3be8e7d95a', max_length=10),
        ),
    ]
