# Generated by Django 4.2.2 on 2023-07-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0005_alter_depotgr_date_alter_ordergr_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotgr',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordergr',
            name='ref',
            field=models.CharField(default='2490b944da', max_length=10),
        ),
    ]
