# Generated by Django 4.2.2 on 2023-07-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0006_alter_depotgr_date_alter_ordergr_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotgr',
            name='heure',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordergr',
            name='ref',
            field=models.CharField(default='bb8a87215a', max_length=10),
        ),
    ]
