# Generated by Django 4.2.2 on 2023-07-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0007_depotgr_heure_alter_ordergr_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergr',
            name='time_create',
        ),
        migrations.AddField(
            model_name='ordergr',
            name='heure',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordergr',
            name='ref',
            field=models.CharField(default='e279456a35', max_length=10),
        ),
    ]
