# Generated by Django 4.2.2 on 2023-07-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0008_remove_ordergr_time_create_ordergr_heure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraisongr',
            name='qts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordergr',
            name='ref',
            field=models.CharField(default='785a3f73da', max_length=10),
        ),
    ]
