# Generated by Django 4.2.2 on 2023-07-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0009_alter_livraisongr_qts_alter_ordergr_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergr',
            name='ref',
            field=models.CharField(default='7a91454656', max_length=10),
        ),
    ]
