# Generated by Django 4.2.2 on 2023-07-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0010_alter_ordergr_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergr',
            name='ref',
            field=models.CharField(default='909cd4e725', max_length=10),
        ),
    ]
