# Generated by Django 4.2.2 on 2023-07-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0011_alter_ordergr_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergr',
            name='ref',
            field=models.CharField(default='42615c3454', max_length=10),
        ),
    ]
