# Generated by Django 4.2.2 on 2023-10-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0013_supplier_alter_ordergr_ref_depotgr_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='ordergr',
            name='ref',
            field=models.CharField(default='abae92cc47', max_length=10),
        ),
    ]
