# Generated by Django 4.2.2 on 2023-10-31 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0014_supplier_phone_alter_ordergr_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergr',
            name='ref',
            field=models.CharField(default='c2725c8f00', max_length=10),
        ),
        migrations.CreateModel(
            name='OrderCmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default='29fb3d100d', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appro.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='LineCmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appro.ordergr')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appro.product')),
            ],
        ),
    ]
