# Generated by Django 4.2.2 on 2023-10-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0015_alter_ordergr_ref_ordercmd_linecmd'),
    ]

    operations = [
        migrations.AddField(
            model_name='linecmd',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordercmd',
            name='ref',
            field=models.CharField(default='7322071133', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordergr',
            name='ref',
            field=models.CharField(default='bf2933e56d', max_length=10),
        ),
    ]
