# Generated by Django 4.2.2 on 2023-10-31 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0016_linecmd_total_price_alter_ordercmd_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linecmd',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appro.ordercmd'),
        ),
        migrations.AlterField(
            model_name='ordercmd',
            name='ref',
            field=models.CharField(default='36eb7fe8f2', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordergr',
            name='ref',
            field=models.CharField(default='b700b0e174', max_length=10),
        ),
    ]
