# Generated by Django 4.2.2 on 2023-10-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appro', '0017_alter_linecmd_order_alter_ordercmd_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercmd',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordercmd',
            name='ref',
            field=models.CharField(default='522a5c5192', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordergr',
            name='ref',
            field=models.CharField(default='ceead88d81', max_length=10),
        ),
    ]
