# Generated by Django 4.2.2 on 2023-07-05 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prod', '0008_alter_depotpt_qts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appro', '0012_alter_ordergr_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.pointvente')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.pointvente')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm.orderfact')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appro.product')),
            ],
        ),
        migrations.CreateModel(
            name='HasQtsCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appro.product')),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.pointvente')),
            ],
        ),
        migrations.CreateModel(
            name='DepotCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm.orderdepot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appro.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.pointvente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
