# Generated by Django 4.2.2 on 2023-11-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0008_alter_depotpt_qts'),
        ('comm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfact',
            name='pv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.pointvente'),
        ),
        migrations.AlterField(
            model_name='orderfact',
            name='ref',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
